imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: true }

web_profiler:
    toolbar: true
    intercept_redirects: false

doctrine:
    orm:
        dql:
            string_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
                DATE: DoctrineExtensions\Query\Mysql\Date
                ROUND: DoctrineExtensions\Query\Mysql\Round
                IFELSE: DoctrineExtensions\Query\Mysql\IfElse
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat


nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
        paths:
            '^/api_bolsamax':
                allow_origin: ['*']
                allow_headers: ['*']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600                




#swiftmailer:
#    delivery_addresses: ['me@example.com']



                
                