# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username    

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        login:
            pattern:  ^/api_hc/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api_hc/login_check
                username_parameter: username
                password_parameter: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false  


        register_step1:
            pattern:   ^/api_hc/p/register_step1
            stateless: true
            anonymous: true   

        register_step2:
            pattern:   ^/api_hc/p/register_step1
            stateless: true
            anonymous: true    

        register_check:
            pattern:   ^/api_hc/p/register_check
            stateless: true
            anonymous: true    

        register_step1:
            pattern:   ^/api_hc/p/register_step1
            stateless: true
            anonymous: true   

        password_reset_step1:
            pattern:   ^/api_hc/p/password_reset_step1
            stateless: true
            anonymous: true    

        password_reset_check:
            pattern:   ^/api_hc/p/password_reset_check
            stateless: true
            anonymous: true 

        password_reset_step2:
            pattern:   ^/api_hc/p/password_reset_step2
            stateless: true
            anonymous: true

        buscar_negocio:
            pattern:   ^/api_hc/p/buscar_negocio
            stateless: true
            anonymous: true

        buscar_horarios:
            pattern:   ^/api_hc/p/buscar_horarios
            stateless: true
            anonymous: true   

        agendar:
            pattern:   ^/api_hc/p/agendar
            stateless: true
            anonymous: true

        confirmacion:
            pattern:   ^/api_hc/p/confirmacion
            stateless: true
            anonymous: true                                                  


        api_hc:
            pattern:   ^/api_hc
            stateless: true
            provider: fos_userbundle
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator


                        


        main:           
            anonymous: ~                       


    access_control:
        - { path: ^/api_hc/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/api_hc/p/buscar_negocio, roles: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/api_hc/p/buscar_horarios, roles: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/api_hc/p/agendar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api_hc/p/confirmacion, roles: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/api_hc/p/register_step1, roles: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/api_hc/p/register_step2, roles: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/api_hc/p/register_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api_hc/p/password_reset_step1, roles: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/api_hc/p/password_reset_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/api_hc/p/password_reset_step2, roles: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/api_hc,       roles: IS_AUTHENTICATED_FULLY }      


            
